name: Node.js CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Cancel workflow on failure
      if: failure()
      run: |
        echo "The workflow has failed. Cancelling the commit..."
        git reset --soft HEAD^
        git commit -m "Automatically cancelled the commit due to workflow failure"
        git push --force
